GET http://localhost:3001/api/persons

###
GET http://localhost:3001/api/persons/1

###

DELETE http://localhost:3001/api/persons/3828783377

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "John Doe II",
  "number": "91-1230494567"
}

###

GET http://localhost:3001/info